import { Status, Subscription } from "@prisma/client";

export const BRAND_LOGOS = [
  {
    name: "netflix",
    icon: "https://seeklogo.com/images/N/netflix-n-logo-0F1ED3EBEB-seeklogo.com.png",
  },
  {
    name: "spotify",
    icon: "https://storage.googleapis.com/pr-newsroom-wp/1/2023/05/Spotify_Primary_Logo_RGB_Green.png",
  },
  {
    name: "youtube",
    icon: "https://goodly.co.in/wp-content/uploads/2023/10/youtube-logo-png-46016-1.png",
  },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 1,
    user_id: "1",
    name: "Netflix",
    cost: 200,
    cycle: "MONTHLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 1),
    icon: "https://seeklogo.com/images/N/netflix-n-logo-0F1ED3EBEB-seeklogo.com.png",
    status: Status.ACTIVE,
    tags: ["Entertainment", "Streaming"],
    description: "Watch your favorite movies and TV shows online.",
  },
  {
    id: 2,
    user_id: "2",
    name: "Spotify",
    cost: 150,
    cycle: "MONTHLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 15),
    icon: "https://storage.googleapis.com/pr-newsroom-wp/1/2023/05/Spotify_Primary_Logo_RGB_Green.png",
    status: Status.ACTIVE,
    tags: ["Music", "Streaming"],
    description: "Listen to your favorite songs and podcasts online.",
  },

  {
    id: 2,
    user_id: "2",
    name: "Youtube",
    cost: 150,
    cycle: "MONTHLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 15),
    icon: "https://goodly.co.in/wp-content/uploads/2023/10/youtube-logo-png-46016-1.png",
    status: Status.ACTIVE,
    tags: ["Video", "Streaming"],
    description: "Watch your favorite videos and channels online.",
  },
  {
    id: 2,
    user_id: "2",
    name: "Twitter",
    cost: 150,
    cycle: "MONTHLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 3),
    icon: "",
    status: Status.ACTIVE,
    tags: ["Social Media", "Communication"],
    description: "Connect with friends and follow your favorite accounts.",
  },
  {
    id: 2,
    user_id: "2",
    name: "Vercel",
    cost: 150,
    cycle: "MONTHLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 15),
    icon: "https://goodly.co.in/wp-content/uploads/2023/10/youtube-logo-png-46016-1.png",
    status: Status.ACTIVE,
    tags: ["Web Hosting", "Deployment"],
    description: "Deploy and host your web applications with ease.",
  },
  {
    id: 3,
    user_id: "3",
    name: "Adobe Creative Cloud",
    cost: 1000,
    cycle: "YEARLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), 0, 1),
    icon: "https://seeklogo.com/images/A/adobe-creative-cloud-logo-09835516CE-seeklogo.com.png",
    status: Status.ACTIVE,
    tags: ["Design", "Editing"],
    description: "Access a suite of creative tools for design and editing.",
  },
  {
    id: 4,
    user_id: "4",
    name: "Amazon Prime",
    cost: 120,
    cycle: "YEARLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), 3, 5),
    icon: "https://seeklogo.com/images/A/amazon-prime-icon-logo-284C9B4A55-seeklogo.com.png",
    status: Status.ACTIVE,
    tags: ["Streaming", "Entertainment"],
    description: "Stream movies, TV shows, and more with Amazon Prime.",
  },
  {
    id: 5,
    user_id: "5",
    name: "Disney+",
    cost: 250,
    cycle: "MONTHLY",
    createdAt: new Date(),
    updatedAt: new Date(),
    startDate: new Date(),
    dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 1),
    icon: "https://seeklogo.com/images/D/disney-logo-F372D69848-seeklogo.com.png",
    status: Status.ACTIVE,
    tags: ["Streaming", "Entertainment"],
    description: "Stream movies, TV shows, and more with Disney+.",
  },
];
